replicaCount: 1
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ''
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
service:
  type: ClusterIP
  port: 80
